export const headerData = [
  { title: "Home", href: "/" },
  { title: "Shop", href: "/Shop" },
  // { title: "Contacts", href: "/contacts" },
  { title: "Blog", href: "/Blog" },
  { title: "Hot deals", href: "/HotDeals" },
];
export const quickLinksData = [
  { title: "About us", href: "/about" },
  { title: "Contact us", href: "/contact" },
  { title: "Terms & Conditions", href: "/terms" },
  { title: "Privacy Policy", href: "/privacy" },
  { title: "FAQs", href: "/faqs" },
  { title: "Help", href: "/help" },
];
export const categoriesData = [
  { title: "Mobiles", href: "mobiles" },
  { title: "Appliances", href: "appliances" },
  { title: "Smartphones", href: "smartphones" },
  { title: "Air Conditioners", href: "air-conditioners" },
  { title: "Washing Machine", href: "washing-machine" },
  { title: "Kitchen Appliances", href: "kitchen-appliances" },
  { title: "gadget accessories", href: "gadget-accessories" },
];
export const productType = [
  { title: "Gadget", value: "gadget" },
  { title: "Appliances", value: "appliances" },
  { title: "Fashion", value: "fashion" },
  { title: "Others", value: "others" },
];

export const categories = [
  { id: "1", name: "Gadget" },
  { id: "2", name: "Appliances" },
  { id: "3", name: "Fashon" },
];

export type popularProducts = {
  id: number;
  name: string;
  price: number;
  description: string;
  rating: number;
  reviews: number;
  inStock: boolean;
  images: string[];
  colors: string[];
  category: string;
  freeDelivery: boolean;
  returnDays: number;
};

export const popularProducts = [
  {
    id: "1",
    name: "IPhone 16 Pro Max",
    price: 1099,
    discount: 10,
    image: "/product_1.png",
    rating: 5.0,
    category: "Gadget",
    instock: true,
    color: ["gold"],
    features: [],
    freeDelivery: true,
    returnDays: 14,
    description:
      "Elevate your mobile experience with the iPhone 16 Pro Max,  engineered for those who demand the absolute best in performance, photography, and battery life. Encased in a refined, ultra-durable titanium design, this flagship device pushes the boundaries of what a smartphone can doa very good phone",
    reviews: 75,
  },
  {
    id: "22",
    name: "Camon 20 Pro",
    price: 620,
    discount: 15,
    image: "/product_22.png",
    rating: 4.0,
    category: "Gadget",
    instock: true,
    color: ["red", "black"],
    features: [],
    freeDelivery: true,
    returnDays: 14,
    description:
      "The Camon series is built entirely around photography and content creation, positioning itself as a budget-to-mid-range powerhouse for mobile shooters",
    reviews: 60,
  },
  {
    id: "3",
    name: "Smart Headphones",
    price: 26,
    discount: 25,
    image: "/product_3.png",
    rating: 3.0,
    category: "Gadget",
    instock: true,
    color: ["red"],
    features: [],
    freeDelivery: true,
    returnDays: 14,
    description:
      "Escape the noise and immerse yourself in pure, high-fidelity audio. The AuraSound Pro combines studio-grade sound quality with industry-leading Active Noise Cancellation (ANC) and an ultra-ergonomic design. Whether you are commuting, working from home, or locking into a high-intensity workout, these headphones deliver an unmatched listening experience that lasts all day.",
    reviews: 45,
  },
  {
    id: "4",
    name: "Smart Watch",
    price: 120,
    discount: 10,
    image: "/product_4.png",
    rating: 5.0,
    category: "Gadget",
    instock: true,
    color: ["Silver", "black"],
    features: [],
    freeDelivery: true,
    returnDays: 14,
    description:
      "Take absolute control of your day, your fitness, and your connectivity with the Smartwatch. Meticulously crafted with an ultra-durable aerospace aluminum frame and a stunning, scratch-resistant AMOLED display, this watch merges timeless style with bleeding-edge technology. Whether you are tracking a high-intensity workout, answering calls on the go, or maximizing your sleep quality, the Apex Nexus acts as your ultimate, 24/7 personal assistant.",
    reviews: 70,
  },
  {
    id: "5",
    name: " HydraClean Pro Washing Machine",
    price: 400,
    discount: 25,
    image: "/product_5.png",
    rating: 4.0,
    category: "Appliances",
    instock: true,
    color: ["white"],
    features: [],
    freeDelivery: true,
    returnDays: 14,
    description:
      "Transform chore day into an effortless experience with the HydraClean Pro. Engineered for modern homes, this high-capacity, front-load washing machine combines advanced stain-removal technology with an ultra-quiet smart inverter motor. Whether you are dealing with delicate silks, heavily soiled gym gear, or a massive load of family bedding, the HydraClean Pro delivers a flawless, hygienic clean while actively protecting your fabrics and your utility bills.",
    reviews: 20,
  },
  {
    id: "6",
    name: "TCL 45 Inch Smart TV",
    price: 350,
    discount: 10,
    image: "/product_6.png",
    rating: 4.0,
    category: "Appliances",
    instock: true,
    color: ["black"],
    features: [],
    freeDelivery: true,
    returnDays: 14,
    description:
      "Experience your favorite movies, sports, and video games like never before with the TCL QLED 4K Smart TV. Combining cutting-edge Quantum Dot technology with a sleek, bezel-less design, this television delivers breathtakingly vivid colors, deep contrast, and striking clarity. Powered by Google TV, it brings together your favorite streaming apps, live channels, and smart home controls into one seamless, ultra-responsive hub.",
    reviews: 100,
  },
  {
    id: "26",
    name: "Playstation Pro",
    price: 799,
    discount: 10,
    image: "/product_26.png",
    rating: 5.0,
    category: "Gadget",
    instock: true,
    color: ["WHite"],
    features: [],
    freeDelivery: true,
    returnDays: 14,
    description: "Step into a bold new era of interactive entertainment with the PlayStation 5. Engineered with a custom, ultra-high-speed Solid State Drive (SSD), the PS5 eliminates loading screens entirely, pulling you instantly into sprawling, cinematic worlds. With breathtaking 4K graphics, ultra-smooth 120Hz gameplay, and deeply immersive spatial audio, this is not just a console—it is a gateway to the future of gaming.",
    reviews: 50,
  },

  {
    id: "27",
    name: "Samsung S23",
    price: 400,
    discount: 15,
    image: "/product_27.png",
    rating: 4.0,
    category: "Gadget",
    instock: true,
    color: ["light pink"],
    features: [],
    freeDelivery: true,
    returnDays: 14,
    description: "Upgrade your daily mobile experience with the Samsung Galaxy S23. Designed for those who want flagship-tier power in a sleek, compact, and comfortable form factor, this smartphone brings together striking aesthetics and massive internal upgrades. From capturing brilliant, clear photos in the dark to seamless multitasking and elite gaming, the Galaxy S23 is built to keep up with your lifestyle without breaking a sweat.",
    reviews: 60,
  },
  {
    id: "9",
    name: "2 in 1 Waterheater and Flask",
    price: 56,
    discount: 25,
    image: "/product_9.png",
    rating: 4.0,
    category: "Appliances",
    instock: true,
    color: ["red"],
    features: [],
    freeDelivery: true,
    returnDays: 14,
    description: "Enjoy hot coffee, tea, or instant meals wherever life takes you. This innovative 2-in-1 Smart Travel Flask completely replaces bulky traditional kettles and fragile thermos flasks. It allows you to boil fresh water in minutes and instantly seals to lock in that piping-hot temperature for hours. Designed for travelers, office professionals, students, and busy parents, it gives you hot water on demand, completely un-tethered from a kitchen.",
    reviews: 70,
  },
  {
    id: "19",
    name: "Ice maker cool fridge",
    price: 1099,
    discount: 10,
    image: "/product_19.png",
    rating: 5.0,
    category: "Appliances",
    instock: true,
    color: ["blue"],
    features: [],
    freeDelivery: true,
    returnDays: 14,
    description: "Upgrade your hosting game and keep the refreshments flowing with the ultimate 2-in-1 Ice Maker & Beverage Refrigerator. Engineered for entertainment spaces, home bars, offices, and RVs, this premium appliance combines a lightning-fast automatic ice maker and a precision-chilled beverage fridge into one sleek, space-saving countertop unit. No more running to the kitchen for ice or drinking lukewarm beverages—everything you need for the perfect drink is right at your fingertips.",
    reviews: 35,
  }, 

  {
     id: "29",
    name: "Soccer Boot",
    price: 80,
    discount: 5,
    image: "/product_29.png",
    rating: 3.0,
    category: "Fashion",
    instock: true,
    color: ["yellow"],
    features: [],
    freeDelivery: true,
    returnDays: 14,
    description: "",
    reviews: 45,
  },
  {
     id: "30",
    name: "Gucci Bag",
    price: 800,
    discount: 5,
    image: "/product_30.png",
    rating: 3.0,
    category: "Fashion",
    instock: true,
    color: ["brown"],
    features: [],
    freeDelivery: true,
    returnDays: 14,
    description: "",
    reviews: 65,
  },
  {
     id: "31",
    name: "Red waterProot jacket",
    price: 100,
    discount: 5,
    image: "/product_31.png",
    rating: 4.0,
    category: "Fashion",
    instock: true,
    color: ["red"],
    features: [],
    freeDelivery: true,
    returnDays: 14,
    description: "",
    reviews: 68,
  },
  {
     id: "32",
    name: "Black leather jacket",
    price: 82,
    discount: 5,
    image: "/product_32.png",
    rating: 4.0,
    category: "Fashion",
    instock: true,
    color: ["black"],
    features: [],
    freeDelivery: true,
    returnDays: 14,
    description: "",
    reviews: 80,
  }
];

export const shopProducts = [
  {
    id: "1",
    name: "IPhone 16 Pro Max",
    price: 1099,
    discount: 10,
    image: "/product_1.png",
    rating: 5.0,
    category: "Gadget",
    instock: true,
    color: ["Silver", "gold"],
    features: [],
  },
  {
    id: "22",
    name: "Camon 20 Pro",
    price: 620,
    discount: 15,
    image: "/product_22.png",
    rating: 4.0,
    category: "Gadget",
    instock: true,
    color: ["red", "black"],
    features: [],
  },
  {
    id: "3",
    name: "Smart Headphones",
    price: 26,
    discount: 25,
    image: "/product_3.png",
    rating: 3.0,
    category: "Gadget",
    instock: true,
    color: ["red"],
    features: [],
  },
  {
    id: "4",
    name: "Smart Watch",
    price: 120,
    discount: 10,
    image: "/product_4.png",
    rating: 5.0,
    category: "Gadget",
    instock: true,
    color: ["Silver", "black"],
    features: [],
  },
  {
    id: "5",
    name: "Washing Machine",
    price: 400,
    discount: 25,
    image: "/product_5.png",
    rating: 4.0,
    category: "Appliances",
    instock: true,
    color: ["white"],
    features: [],
  },
  {
    id: "6",
    name: "TCL 45 Inch Smart TV",
    price: 350,
    discount: 10,
    image: "/product_6.png",
    rating: 4.0,
    category: "Appliances",
    instock: true,
    color: ["black"],
    features: [],
  },
  {
    id: "7",
    name: "Low power solar fan",
    price: 39,
    discount: 10,
    image: "/product_7.png",
    rating: 3.0,
    category: "Appliances",
    instock: true,
    color: ["Silver", "gold"],
    features: [],
  },
  {
    id: "8",
    name: "2 in 1 Smart monitor and keyboard",
    price: 400,
    discount: 15,
    image: "/product_8.png",
    rating: 4.0,
    category: "Gadget",
    instock: true,
    color: ["red", "black"],
    features: [],
  },
  {
    id: "9",
    name: "2 in 1 Waterheater and Flask",
    price: 56,
    discount: 25,
    image: "/product_9.png",
    rating: 4.0,
    category: "Appliances",
    instock: true,
    color: ["red"],
    features: [],
  },
  {
    id: "10",
    name: "JBL Super laod mini speaker",
    price: 40,
    discount: 10,
    image: "/product_10.png",
    rating: 5.0,
    category: "Gadget",
    instock: true,
    color: ["Silver", "black"],
    features: [],
  },
  {
    id: "11",
    name: "Apple Mifi",
    price: 400,
    discount: 25,
    image: "/product_11.png",
    rating: 4.0,
    category: "Gadget",
    instock: true,
    color: ["white"],
    features: [],
  },
  {
    id: "12",
    name: "Detachable Vacumm base",
    price: 350,
    discount: 10,
    image: "/product_12.png",
    rating: 4.0,
    category: "Appliances",
    instock: true,
    color: ["red"],
    features: [],
  },
  {
    id: "13",
    name: "Dell MAgnitude 48",
    price: 409,
    discount: 10,
    image: "/product_13.png",
    rating: 5.0,
    category: "Gadget",
    instock: true,
    color: ["Silver", "gold"],
    features: [],
  },
  {
    id: "14",
    name: "Samsung note24",
    price: 620,
    discount: 15,
    image: "/product_14.png",
    rating: 4.0,
    category: "Gadget",
    instock: true,
    color: ["skyblue"],
    features: [],
  },
  {
    id: "15",
    name: "Smart phone",
    price: 180,
    discount: 25,
    image: "/product_15.png",
    rating: 3.0,
    category: "Gadget",
    instock: true,
    color: ["mint green"],
    features: [],
  },
  {
    id: "16",
    name: " Sony headphone",
    price: 120,
    discount: 10,
    image: "/product_16.png",
    rating: 5.0,
    category: "Gadget",
    instock: true,
    color: ["pink"],
    features: [],
  },
  {
    id: "17",
    name: "Convertable solar deep freezer",
    price: 400,
    discount: 25,
    image: "/product_17.png",
    rating: 4.0,
    category: "Appliances",
    instock: true,
    color: ["white"],
    features: [],
  },
  {
    id: "18",
    name: "Hisence double cool fridge",
    price: 350,
    discount: 10,
    image: "/product_18.png",
    rating: 4.0,
    category: "Appliances",
    instock: true,
    color: ["blue"],
    features: [],
  },
  {
    id: "19",
    name: "Ice maker cool fridge",
    price: 1099,
    discount: 10,
    image: "/product_19.png",
    rating: 5.0,
    category: "Appliance",
    instock: true,
    color: ["blue"],
    features: [],
  },
  {
    id: "20",
    name: "Smart TV set",
    price: 620,
    discount: 15,
    image: "/product_20.png",
    rating: 4.0,
    category: "Gadget",
    instock: true,
    color: ["black"],
    features: [],
  },
  {
    id: "21",
    name: "Oriamo Earbuds",
    price: 40,
    discount: 5,
    image: "/product_21.png",
    rating: 3.0,
    category: "Gadget",
    instock: true,
    color: ["white"],
    features: [],
  },
  {
    id: "23",
    name: "Super blade blender",
    price: 120,
    discount: 10,
    image: "/product_23.png",
    rating: 5.0,
    category: "Appliance",
    instock: true,
    color: ["WHite"],
    features: [],
  },

  {
    id: "24",
    name: "Asus Gaming Laptop",
    price: 620,
    discount: 15,
    image: "/product_24.png",
    rating: 4.0,
    category: "Gadget",
    instock: true,
    color: ["black"],
    features: [],
  },
  {
    id: "25",
    name: "Wireless Xbox Controller",
    price: 120,
    discount: 5,
    image: "/product_25.png",
    rating: 4.0,
    category: "Gadget",
    instock: true,
    color: ["white", "black"],
    features: [],
  },
  {
    id: "26",
    name: "Playstation Pro",
    price: 799,
    discount: 10,
    image: "/product_26.png",
    rating: 5.0,
    category: "Gadget",
    instock: true,
    color: ["WHite"],
    features: [],
  },

  {
    id: "27",
    name: "Samsung S23",
    price: 400,
    discount: 15,
    image: "/product_27.png",
    rating: 4.0,
    category: "Gadget",
    instock: true,
    color: ["light pink"],
    features: [],
  },
  {
    id: "28",
    name: "Samsung Smartwatch",
    price: 80,
    discount: 5,
    image: "/product_28.png",
    rating: 3.0,
    category: "Gadget",
    instock: true,
    color: ["white"],
    features: [],
  },
  
  {
     id: "29",
    name: "Soccer Boot",
    price: 80,
    discount: 5,
    image: "/product_29.png",
    rating: 3.0,
    category: "Fashion",
    instock: true,
    color: ["yellow"],
    features: [],
    freeDelivery: true,
    returnDays: 14,
    description: "",
    reviews: 45,
  },
  {
     id: "30",
    name: "Gucci Bag",
    price: 800,
    discount: 5,
    image: "/product_30.png",
    rating: 3.0,
    category: "Fashion",
    instock: true,
    color: ["brown"],
    features: [],
    freeDelivery: true,
    returnDays: 14,
    description: "",
    reviews: 65,
  },
  {
     id: "31",
    name: "Red waterProot jacket",
    price: 100,
    discount: 5,
    image: "/product_31.png",
    rating: 4.0,
    category: "Fashion",
    instock: true,
    color: ["red"],
    features: [],
    freeDelivery: true,
    returnDays: 14,
    description: "",
    reviews: 68,
  },
  {
     id: "32",
    name: "Black leather jacket",
    price: 82,
    discount: 5,
    image: "/product_32.png",
    rating: 4.0,
    category: "Fashion",
    instock: true,
    color: ["black"],
    features: [],
    freeDelivery: true,
    returnDays: 14,
    description: "",
    reviews: 80,
  }
];

export type BlogCategory =
  | "All"
  | "Shopping Tips"
  | "Style & Trends"
  | "Tech & Gadgets"
  | "Deals"
  | "Guide";

export interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  category: Exclude<BlogCategory, "All">;
  author: string;
  date: string;
  readTime: number;
  slug: string;
  featured?: boolean;
  icon: string;
  colorTheme: "green" | "amber" | "blue" | "pink" | "purple" | "red";
}

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    title: "Top 10 Gadgets Worth Buying in 2025",
    excerpt:
      "From flagship smartphones to sleek smartwatches, we break down the gadgets that genuinely deserve a spot in your cart this year — no fluff, just honest picks.",
    category: "Tech & Gadgets",
    author: "Jayjay",
    date: "Jun 1, 2025",
    readTime: 5,
    slug: "top-10-gadgets-2025",
    featured: true,
    icon: "smartphone",
    colorTheme: "blue",
  },
  {
    id: "2",
    title: "How to Never Miss a Flash Sale Again",
    excerpt:
      "Set up alerts, wishlist the right items, and be first in line when prices drop.",
    category: "Deals",
    author: "Jayjay",
    date: "May 28, 2025",
    readTime: 3,
    slug: "never-miss-flash-sale",
    icon: "tag",
    colorTheme: "amber",
  },
  {
    id: "3",
    title: "Fashion Pieces That Are Trending Right Now",
    excerpt:
      "Our style team curated the most-loved fashion arrivals of the season.",
    category: "Style & Trends",
    author: "Jayjay",
    date: "May 22, 2025",
    readTime: 4,
    slug: "fashion-trends-2025",
    icon: "shirt",
    colorTheme: "pink",
  },
  {
    id: "4",
    title: "5 Smart Ways to Shop Online and Save More",
    excerpt:
      "Little-known tricks that experienced shoppers use to stretch their budget.",
    category: "Shopping Tips",
    author: "Jayjay",
    date: "May 15, 2025",
    readTime: 4,
    slug: "smart-ways-to-shop-online",
    icon: "shoppingCart",
    colorTheme: "green",
  },
  {
    id: "5",
    title: "Wireless Audio in 2025: What's Actually Worth It?",
    excerpt:
      "We tested the most popular headphones and earbuds so you don't have to.",
    category: "Tech & Gadgets",
    author: "Jayjay",
    date: "May 10, 2025",
    readTime: 6,
    slug: "wireless-audio-2025",
    icon: "headphones",
    colorTheme: "blue",
  },
  {
    id: "6",
    title: "Appliances Buying Guide for Every Budget",
    excerpt:
      "From washing machines to smart TVs — what to look for before you buy.",
    category: "Guide",
    author: "Jayjay",
    date: "May 5, 2025",
    readTime: 7,
    slug: "appliances-buying-guide",
    icon: "home",
    colorTheme: "purple",
  },
  {
    id: "7",
    title: "Gift Ideas for Every Occasion Under $50",
    excerpt:
      "Thoughtful presents that don't break the bank — curated with care.",
    category: "Deals",
    author: "Jayjay",
    date: "Apr 30, 2025",
    readTime: 3,
    slug: "gift-ideas-under-50",
    icon: "gift",
    colorTheme: "red",
  },
];

export const filterCategories: BlogCategory[] = [
  "All",
  "Shopping Tips",
  "Style & Trends",
  "Tech & Gadgets",
  "Deals",
];
